/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Activity;
import java.text.DecimalFormat;
/**
 *
 * @author WS
 */
public class Calculator extends javax.swing.JFrame {
      
        
        double firstnum;
        double secondnum;
        double result;
        String operations;
        String answer;
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblOutput = new javax.swing.JLabel();
        btnC = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btnModulo = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnPN = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnDecimal = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCE1 = new javax.swing.JButton();

        jButton5.setText("jButton1");

        jButton6.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOutput.setBackground(new java.awt.Color(255, 255, 255));
        lblOutput.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblOutput.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOutput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36))); // NOI18N
        lblOutput.setOpaque(true);
        jPanel1.add(lblOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 400, 60));

        btnC.setBackground(new java.awt.Color(255, 102, 0));
        btnC.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnC.setText("C");
        btnC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        jPanel1.add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 91, 80));

        btnCE.setBackground(new java.awt.Color(255, 102, 0));
        btnCE.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnCE.setText("CE");
        btnCE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });
        jPanel1.add(btnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, 80));

        btnModulo.setBackground(new java.awt.Color(255, 102, 0));
        btnModulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnModulo.setText("%");
        btnModulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloActionPerformed(evt);
            }
        });
        jPanel1.add(btnModulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 88, 80));

        btnDivide.setBackground(new java.awt.Color(255, 153, 0));
        btnDivide.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnDivide.setText("/");
        btnDivide.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        jPanel1.add(btnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 90, 80));

        btn7.setBackground(new java.awt.Color(153, 255, 255));
        btn7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn7.setText("7");
        btn7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 90, 69));

        btn8.setBackground(new java.awt.Color(153, 255, 255));
        btn8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn8.setText("8");
        btn8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 91, 69));

        btn9.setBackground(new java.awt.Color(153, 255, 255));
        btn9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn9.setText("9");
        btn9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 90, 69));

        btnMultiply.setBackground(new java.awt.Color(255, 153, 0));
        btnMultiply.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnMultiply.setText("x");
        btnMultiply.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });
        jPanel1.add(btnMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 90, 69));

        btn4.setBackground(new java.awt.Color(153, 255, 255));
        btn4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn4.setText("4");
        btn4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 90, 69));

        btn5.setBackground(new java.awt.Color(153, 255, 255));
        btn5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn5.setText("5");
        btn5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 90, 69));

        btn6.setBackground(new java.awt.Color(153, 255, 255));
        btn6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn6.setText("6");
        btn6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 88, 69));

        btnSub.setBackground(new java.awt.Color(255, 153, 0));
        btnSub.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnSub.setText("-");
        btnSub.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });
        jPanel1.add(btnSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 90, 69));

        btn1.setBackground(new java.awt.Color(153, 255, 255));
        btn1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn1.setText("1");
        btn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 90, 69));

        btn2.setBackground(new java.awt.Color(153, 255, 255));
        btn2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn2.setText("2");
        btn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 91, 69));

        btn3.setBackground(new java.awt.Color(153, 255, 255));
        btn3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn3.setText("3");
        btn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 90, 69));

        btnAdd.setBackground(new java.awt.Color(255, 153, 0));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnAdd.setText("+");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 90, 69));

        btnPN.setBackground(new java.awt.Color(255, 102, 0));
        btnPN.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnPN.setText("+/-");
        btnPN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPNActionPerformed(evt);
            }
        });
        jPanel1.add(btnPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 90, 69));

        btn0.setBackground(new java.awt.Color(255, 102, 0));
        btn0.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn0.setText("0");
        btn0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 91, 69));

        btnDecimal.setBackground(new java.awt.Color(255, 102, 0));
        btnDecimal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnDecimal.setText(".");
        btnDecimal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecimalActionPerformed(evt);
            }
        });
        jPanel1.add(btnDecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 90, 69));

        btnEquals.setBackground(new java.awt.Color(255, 102, 0));
        btnEquals.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnEquals.setText("=");
        btnEquals.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });
        jPanel1.add(btnEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 90, 69));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 60));

        btnCE1.setBackground(new java.awt.Color(204, 204, 204));
        btnCE1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnCE1.setText("CE");
        btnCE1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCE1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
       if (!lblOutput.getText().equals("Error")) {
    String EnterNumber = lblOutput.getText() + btn8.getText();
    lblOutput.setText(EnterNumber);
}

    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if (!lblOutput.getText().equals("Error")) {
    String EnterNumber = lblOutput.getText() + btn7.getText();
    lblOutput.setText(EnterNumber);
}

    }//GEN-LAST:event_btn7ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if (!lblOutput.getText().equals("Error")) {
    String EnterNumber = lblOutput.getText() + btn4.getText();
    lblOutput.setText(EnterNumber);
}

    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
      if (!lblOutput.getText().equals("Error")) {
    String EnterNumber = lblOutput.getText() + btn5.getText();
    lblOutput.setText(EnterNumber);
}

    }//GEN-LAST:event_btn5ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if (!lblOutput.getText().equals("Error")) {
    String EnterNumber = lblOutput.getText() + btn9.getText();
    lblOutput.setText(EnterNumber);
}

    }//GEN-LAST:event_btn9ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
       if (!lblOutput.getText().equals("Error")) {
    String EnterNumber = lblOutput.getText() + btn6.getText();
    lblOutput.setText(EnterNumber);
}

    }//GEN-LAST:event_btn6ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        if (!lblOutput.getText().equals("Error")) {
    String EnterNumber = lblOutput.getText() + btn0.getText();
    lblOutput.setText(EnterNumber);
}

    }//GEN-LAST:event_btn0ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if (!lblOutput.getText().equals("Error")) {
    String EnterNumber = lblOutput.getText() + btn2.getText();
    lblOutput.setText(EnterNumber);
}

    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if (!lblOutput.getText().equals("Error")) {
    String EnterNumber = lblOutput.getText() + btn3.getText();
    lblOutput.setText(EnterNumber);
}

    }//GEN-LAST:event_btn3ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if (!lblOutput.getText().equals("Error")) {
    String EnterNumber = lblOutput.getText() + btn1.getText();
    lblOutput.setText(EnterNumber);
}

    }//GEN-LAST:event_btn1ActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
        lblOutput.setText("");
    }//GEN-LAST:event_btnCActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (!lblOutput.getText().equals("Error")) {
        try {
            firstnum = Double.parseDouble(lblOutput.getText());
            lblOutput.setText("");
            operations = "+";
        } catch (NumberFormatException e) {
            lblOutput.setText("Error");
        }
    }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        // TODO add your handling code here:
      if (!lblOutput.getText().equals("Error")) {
        try {
            firstnum = Double.parseDouble(lblOutput.getText());
            lblOutput.setText("");
            operations = "*";
        } catch (NumberFormatException e) {
            lblOutput.setText("Error");
        }
    }
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
        // TODO add your handling code here:
          if (!lblOutput.getText().equals("Error")) {
        try {
            firstnum = Double.parseDouble(lblOutput.getText());
            lblOutput.setText("");
            operations = "-";
        } catch (NumberFormatException e) {
            lblOutput.setText("Error");
        }
    }
    }//GEN-LAST:event_btnSubActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        // TODO add your handling code here:
      if (!lblOutput.getText().equals("Error")) {
        try {
            firstnum = Double.parseDouble(lblOutput.getText());
            lblOutput.setText("");
            operations = "/";
        } catch (NumberFormatException e) {
            lblOutput.setText("Error");
        }
    }
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloActionPerformed
        // TODO add your handling code here:
      if (!lblOutput.getText().equals("Error")) {
        try {
            firstnum = Double.parseDouble(lblOutput.getText());
            lblOutput.setText("");
            operations = "%";
        } catch (NumberFormatException e) {
            lblOutput.setText("Error");
        }
    }
    }//GEN-LAST:event_btnModuloActionPerformed

    private void btnPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPNActionPerformed
        // TODO add your handling code here:
        double ops = Double.parseDouble(lblOutput.getText());
    ops = ops * (-1);
    DecimalFormat df = new DecimalFormat("#.##"); // Format pattern to remove trailing zeroes
    lblOutput.setText(df.format(ops));
    }//GEN-LAST:event_btnPNActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        // TODO add your handling code here:
        String backspace = null;
    
    // Check if the current text is not equal to "Error"
    if (!lblOutput.getText().equals("Error") && lblOutput.getText().length() > 0) {
        StringBuilder strB = new StringBuilder(lblOutput.getText());
        strB.deleteCharAt(lblOutput.getText().length() - 1);
        backspace = strB.toString();
        lblOutput.setText(backspace);
        }
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
        String answer;
    secondnum = Double.parseDouble(lblOutput.getText());
    DecimalFormat df = new DecimalFormat("#.##");

    if (operations.equals("+")) {
        result = firstnum + secondnum;
    } else if (operations.equals("-")) {
        result = firstnum - secondnum;
    } else if (operations.equals("*")) {
        result = firstnum * secondnum;
    } else if (operations.equals("/")) {
        result = firstnum / secondnum;
    } else if (operations.equals("%")) {
        result = firstnum % secondnum;
    }

    answer = df.format(result);

    // Check if the answer length is greater than a certain threshold (for example, 10 characters)
    if (answer.length() > 10) {
        lblOutput.setText("Error");
    } else {
        lblOutput.setText(answer);
    }
        
    }//GEN-LAST:event_btnEqualsActionPerformed

    private void btnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecimalActionPerformed
        // TODO add your handling code here:
        if (!lblOutput.getText().equals("Error")) {
    String EnterNumber = lblOutput.getText() + btnDecimal.getText();
    lblOutput.setText(EnterNumber);
}

    }//GEN-LAST:event_btnDecimalActionPerformed

    private void btnCE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCE1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCE1;
    private javax.swing.JButton btnDecimal;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnModulo;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnPN;
    private javax.swing.JButton btnSub;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblOutput;
    // End of variables declaration//GEN-END:variables
}
